title: CAKSUP BLOG
description: Jekyll Theme Minimal Resume
username: caksup
user_description: >-
  I\'m a nomad Software Engineer, always searching for the next challenge; no
  task is too scary nor too difficult. Lately I have been immersed in the
  <b>crypto-world</b> working for Radix, a London based startup trying to create
  the next massive scalable DLT. I'm one of the two guys behind all the JS
  related stuff.
user_title: Software Engineer
email: mauriurraco@gmail.com
exclude:
  - package.json
  - src
  - node_modules
baseurl: 'https://caksup.github.io/blog/'
url: 'https://caksup.github.io/blog/'
